# КЛИЕНТСКИЙ БОТ
BTN_START = "Начать"
BTN_REGISTER = "Зарегистрироваться"
BTN_PROFILE = "Мой профиль"
BTN_GEN_CODE = "Получить код для оплаты"
BTN_FEEDBACK = "Обратная связь"
BTN_BACK = "Назад в меню"
BTN_CONFIRM = "Подтвердить"

BTN_GEN_NEW_CODE = "Сгенерировать новый код"

# Обратная связь
BTN_LEAVE_FEEDBACK = "Оставить отзыв"
BTN_LEAVE_IDEA = "Предложить идею"
BTN_CONTACT_ADMIN = "Связаться с руководством"
BTN_SCORE_1 = "1"
BTN_SCORE_2 = "2"
BTN_SCORE_3 = "3"
BTN_SCORE_4 = "4"
BTN_SCORE_5 = "5"
BTN_SCORE_6 = "6"
BTN_SCORE_7 = "7"
BTN_SCORE_8 = "8"
BTN_SCORE_9 = "9"
BTN_SCORE_10 = "10"
BTN_SEND = "Отправить"
BTN_BACK_FEEDBACK = "Назад"

# БАРИСТА-БОТ
BTN_ORDER = "Обработка заказа"
BTN_CREATE_NOTIFICATION = "Создать уведомление"
BTN_GIFT = "Подарить подарок"
BTN_WRITEOFF_GIFT = "Списать подарок"
BTN_HISTORY = "История операций"
BTN_ORDER_CREATE = "Создать заказ"
BTN_ORDER_REFUND = "Возврат"
BTN_CONFIRM_REFUND = "Подтвердить возврат"
BTN_SEND_NOTIFICATION_ALL = "Для всех пользователей"
BTN_SEND_NOTIFICATION_ONE = "Для одного пользователя"
BTN_ORDER_POINTS = "Списать баллы"
BTN_ORDER_ACCUMULATE = "Накопить баллы"
BTN_HISTORY_NEXT = "Дальше"
BTN_HISTORY_PREV = "Назад"

# АДМИНКА (web)
BTN_ADMIN_LOGIN = "Войти"
BTN_ADMIN_LOGOUT = "Выйти"
BTN_ADMIN_USERS = "Пользователи"
BTN_ADMIN_ORDERS = "Заказы"
BTN_ADMIN_FEEDBACKS = "Отзывы"
BTN_ADMIN_IDEAS = "Идеи"
BTN_ADMIN_GIFTS = "Подарки"
BTN_ADMIN_ANALYTICS = "Аналитика"
BTN_ADMIN_NOTIFICATIONS = "Рассылки"
BTN_ADMIN_MANUAL_BALANCE = "Ручное начисление/списание"
